name: localization
description: Package to simplify the package translation.
version: 2.1.0
homepage: https://github.com/Flutterando/localization

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutterando_analysis: ^0.0.1+1
  

flutter:
  assets:
    - example/assets/img/
    - test/assets/lang/
    - test/assets/lang2/
